name: Build and deploy to dev

on: 
  push:
    branches: 
      - dev

env:
  APP_SERVICE_NAME: helloWithFlask
  DOCKER_IMAGE: flaskwebapp
  DOCKER_TAG: "1.0.0"
      
jobs:
  build-and-deploy-prod:
    environment: dev
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      with:
        ref: 'dev'
     
    - name: Build and push container image to registry 
      id: container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        dockerfile: Dockerfile
        image: ${{ env.DOCKER_IMAGE}}
        registry: ${{ secrets.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        tags: ${{env.DOCKER_TAG}}
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.APP_SERVICE_NAME}}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{secrets.REGISTRY_HOST}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_TAG}}